FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY pages   /usr/share/nginx/html/pages
COPY styles  /usr/share/nginx/html/styles
COPY scripts /usr/share/nginx/html/scripts
COPY assets  /usr/share/nginx/html/assets
